CREATE TABLE "TB_COMPANIES" (
	"id"	UUID		NOT NULL,
	"imageId"	UUID		NULL,
	"description"	TEXT		NULL,
	"name"	VARCHAR		NOT NULL,
	"address"	VARCHAR		NOT NULL,
	"email"	VARCHAR		NOT NULL,
	"phone"	VARCHAR		NOT NULL,
	"businessReg"	VARCHAR		NOT NULL,
	"traderReg"	VARCHAR		NOT NULL
);

COMMENT ON COLUMN "TB_COMPANIES"."id" IS '회사 ID';

COMMENT ON COLUMN "TB_COMPANIES"."imageId" IS '사진 파일 ID';

COMMENT ON COLUMN "TB_COMPANIES"."description" IS '회사 소개';

COMMENT ON COLUMN "TB_COMPANIES"."name" IS '회사명';

COMMENT ON COLUMN "TB_COMPANIES"."address" IS '회사주소';

COMMENT ON COLUMN "TB_COMPANIES"."email" IS '회사메일';

COMMENT ON COLUMN "TB_COMPANIES"."phone" IS '회사전화';

COMMENT ON COLUMN "TB_COMPANIES"."businessReg" IS '법인등록번호';

COMMENT ON COLUMN "TB_COMPANIES"."traderReg" IS '사업자등록번호';

CREATE TABLE "TB_PROFILE_POSITIONS" (
	"id"	UUID		NOT NULL,
	"positionId"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL
);

COMMENT ON COLUMN "TB_PROFILE_POSITIONS"."id" IS '프로필 직무';

COMMENT ON COLUMN "TB_PROFILE_POSITIONS"."positionId" IS '직무 ID';

COMMENT ON COLUMN "TB_PROFILE_POSITIONS"."profileId" IS '프로필 ID';

CREATE TABLE "TB_POSITIONS" (
	"id"	UUID		NOT NULL,
	"companyId"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"description"	TEXT		NULL
);

COMMENT ON COLUMN "TB_POSITIONS"."id" IS '직무 ID';

COMMENT ON COLUMN "TB_POSITIONS"."companyId" IS '회사 ID';

COMMENT ON COLUMN "TB_POSITIONS"."name" IS '직무명';

COMMENT ON COLUMN "TB_POSITIONS"."description" IS '직무설명';

CREATE TABLE "TB_LEAVES" (
	"id"	UUID		NOT NULL,
	"leaveBalanceId"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL,
	"startAt"	TIMESTAMP		NOT NULL,
	"finishAt"	TIMESTAMP		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_LEAVES"."id" IS '사용 휴가 ID';

COMMENT ON COLUMN "TB_LEAVES"."leaveBalanceId" IS '보유 휴가 ID';

COMMENT ON COLUMN "TB_LEAVES"."profileId" IS '프로필 ID';

COMMENT ON COLUMN "TB_LEAVES"."startAt" IS '휴가 시작 일자';

COMMENT ON COLUMN "TB_LEAVES"."finishAt" IS '휴가 종료 일자';

COMMENT ON COLUMN "TB_LEAVES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_LEAVES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_DOCUMENT_FILES" (
	"id"	UUID		NOT NULL,
	"pageId"	UUID		NOT NULL,
	"fileId"	UUID		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_DOCUMENT_FILES"."id" IS '문서첨부파일 ID';

COMMENT ON COLUMN "TB_DOCUMENT_FILES"."pageId" IS '문서 ID';

COMMENT ON COLUMN "TB_DOCUMENT_FILES"."fileId" IS '파일 ID';

COMMENT ON COLUMN "TB_DOCUMENT_FILES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_DOCUMENT_FILES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_COMPANY_POLICIES" (
	"id"	UUID		NOT NULL,
	"companyId"	UUID		NOT NULL,
	"workPolicyId"	UUID		NULL,
	"leavePolicyId"	UUID		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."id" IS '회사정책 ID';

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."companyId" IS '회사 ID';

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."workPolicyId" IS '근로 정책 ID';

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."leavePolicyId" IS '휴가정책 ID';

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_COMPANY_POLICIES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_DOCUMENTS" (
	"id"	UUID		NOT NULL,
	"companyId"	UUID		NOT NULL,
	"creatorId"	UUID		NOT NULL,
	"title"	VARCHAR		NOT NULL,
	"content"	TEXT		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_DOCUMENTS"."id" IS '문서 ID';

COMMENT ON COLUMN "TB_DOCUMENTS"."companyId" IS '회사';

COMMENT ON COLUMN "TB_DOCUMENTS"."creatorId" IS '생성자 프로필 ID';

COMMENT ON COLUMN "TB_DOCUMENTS"."title" IS '문서 제목';

COMMENT ON COLUMN "TB_DOCUMENTS"."content" IS '문서 내용';

COMMENT ON COLUMN "TB_DOCUMENTS"."createdAt" IS '문서 생성일자';

COMMENT ON COLUMN "TB_DOCUMENTS"."updatedAt" IS '문서 수정일자';

CREATE TABLE "TB_BANKS" (
	"id"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL
);

COMMENT ON COLUMN "TB_BANKS"."id" IS '은행 ID';

COMMENT ON COLUMN "TB_BANKS"."name" IS '은행 이름';

CREATE TABLE "TB_PROFILES" (
	"id"	UUID		NOT NULL,
	"userId"	UUID		NOT NULL,
	"companyId"	UUID		NULL,
	"email"	VARCHAR		NOT NULL,
	"accessToken"	VARCHAR		NULL,
	"refreshToken"	VARCHAR		NULL,
	"provider"	ENUM		NOT NULL,
	"role"	ENUM		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_PROFILES"."id" IS '프로필 ID';

COMMENT ON COLUMN "TB_PROFILES"."userId" IS '사용자 ID';

COMMENT ON COLUMN "TB_PROFILES"."companyId" IS '소속 회사 ID';

COMMENT ON COLUMN "TB_PROFILES"."email" IS '이메일, UNIQUE';

COMMENT ON COLUMN "TB_PROFILES"."accessToken" IS '소셜 계정 액세스 토큰';

COMMENT ON COLUMN "TB_PROFILES"."refreshToken" IS '소셜 계정 리프레쉬 토큰';

COMMENT ON COLUMN "TB_PROFILES"."provider" IS '소셜 계정 제공자';

COMMENT ON COLUMN "TB_PROFILES"."role" IS '계정 역할';

COMMENT ON COLUMN "TB_PROFILES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_PROFILES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_TEAM_PROFILES" (
	"id"	UUID		NOT NULL,
	"teamId"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_TEAM_PROFILES"."id" IS '멤버 ID';

COMMENT ON COLUMN "TB_TEAM_PROFILES"."teamId" IS '팀 ID';

COMMENT ON COLUMN "TB_TEAM_PROFILES"."profileId" IS '프로필 ID';

COMMENT ON COLUMN "TB_TEAM_PROFILES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_TEAM_PROFILES"."updatedAt" IS '수정일자';

CREATE TABLE "REDIS:BREAK_SESSIONS" (
	"{profileId}_break"	UUID+break		NOT NULL,
	"order"	INT		NOT NULL,
	"startAt"	TIMESTAMP		NOT NULL,
	"endAt"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "REDIS:BREAK_SESSIONS"."{profileId}_break" IS '휴게 세션 키값';

COMMENT ON COLUMN "REDIS:BREAK_SESSIONS"."order" IS '근무중 휴게 번호';

COMMENT ON COLUMN "REDIS:BREAK_SESSIONS"."startAt" IS '휴게 시작 시간';

COMMENT ON COLUMN "REDIS:BREAK_SESSIONS"."endAt" IS '휴게 종료 시간';

CREATE TABLE "REDIS:WORK_SESSIONS" (
	"{profileId}_work"	UUID+work		NOT NULL,
	"type"	ENUM		NOT NULL,
	"method"	ENUM		NOT NULL,
	"status"	ENUM		NOT NULL,
	"recordAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "REDIS:WORK_SESSIONS"."{profileId}_work" IS '출근 세션 키값';

COMMENT ON COLUMN "REDIS:WORK_SESSIONS"."type" IS '출퇴근 구분 (출근, 퇴근, ...)';

COMMENT ON COLUMN "REDIS:WORK_SESSIONS"."method" IS '출퇴근 방식 (비콘, GPS, ...)';

COMMENT ON COLUMN "REDIS:WORK_SESSIONS"."status" IS '출퇴근 상태 (근무중, 휴게중, 퇴근함, ...)';

COMMENT ON COLUMN "REDIS:WORK_SESSIONS"."recordAt" IS '기록한 출퇴근 시간';

CREATE TABLE "TB_USERS" (
	"id"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"gender"	ENUM		NOT NULL,
	"birth"	TIMESTAMP		NOT NULL,
	"phone"	VARCHAR		NOT NULL,
	"address"	VARCHAR		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_USERS"."id" IS '사용자 ID';

COMMENT ON COLUMN "TB_USERS"."name" IS '이름(영문/한글)';

COMMENT ON COLUMN "TB_USERS"."gender" IS '성별';

COMMENT ON COLUMN "TB_USERS"."birth" IS '생년월일';

COMMENT ON COLUMN "TB_USERS"."phone" IS 'UNIQUE';

COMMENT ON COLUMN "TB_USERS"."address" IS '개인 주소';

COMMENT ON COLUMN "TB_USERS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_USERS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_BEACONS" (
	"id"	UUID		NOT NULL,
	"companyId"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"type"	ENUM		NOT NULL,
	"location"	GEOGRAPHY		NOT NULL,
	"radius"	INT		NOT NULL,
	"ipAddress"	INET		NULL,
	"macAddress"	MACADDR		NULL,
	"isActive"	BOOLEAN		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_BEACONS"."id" IS '비콘 ID';

COMMENT ON COLUMN "TB_BEACONS"."companyId" IS '회사 ID';

COMMENT ON COLUMN "TB_BEACONS"."name" IS '비콘 이름';

COMMENT ON COLUMN "TB_BEACONS"."type" IS '비콘 유형';

COMMENT ON COLUMN "TB_BEACONS"."location" IS '비콘 위치 좌표';

COMMENT ON COLUMN "TB_BEACONS"."radius" IS '반경 허용 거리(미터)';

COMMENT ON COLUMN "TB_BEACONS"."ipAddress" IS '아이피 주소';

COMMENT ON COLUMN "TB_BEACONS"."macAddress" IS '맥 주소';

COMMENT ON COLUMN "TB_BEACONS"."isActive" IS '활성여부';

COMMENT ON COLUMN "TB_BEACONS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_BEACONS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_ACCOUNT_LOGS" (
	"id"	UUID		NOT NULL,
	"ipAddress"	VARCHAR		NOT NULL,
	"type"	ENUM		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_ACCOUNT_LOGS"."id" IS '계정 로그 ID';

COMMENT ON COLUMN "TB_ACCOUNT_LOGS"."ipAddress" IS '요청아이피주소';

COMMENT ON COLUMN "TB_ACCOUNT_LOGS"."type" IS '로그 유형';

COMMENT ON COLUMN "TB_ACCOUNT_LOGS"."createdAt" IS '생성일자';

CREATE TABLE "TB_TEAMS" (
	"id"	UUID		NOT NULL,
	"companyId"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_TEAMS"."id" IS '팀 ID';

COMMENT ON COLUMN "TB_TEAMS"."companyId" IS '회사 ID';

COMMENT ON COLUMN "TB_TEAMS"."name" IS '팀 이름';

COMMENT ON COLUMN "TB_TEAMS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_TEAMS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_BANK_ACCOUNTS" (
	"id"	UUID		NOT NULL,
	"bankId"	UUID		NOT NULL,
	"userId"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"digits"	INT		NOT NULL,
	"expireAt"	TIMESTAMP		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL,
	"isAuthorized"	BOOLEAN		NOT NULL
);

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."id" IS '은행 계좌 ID';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."bankId" IS '은행 ID';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."userId" IS '사용자 ID';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."name" IS '계좌명';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."digits" IS '계좌번호';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."expireAt" IS '계좌만료일';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."updatedAt" IS '수정일자';

COMMENT ON COLUMN "TB_BANK_ACCOUNTS"."isAuthorized" IS '인증여부';

CREATE TABLE "TB_REQUESTS" (
	"id"	UUID		NOT NULL,
	"creatorId"	UUID		NOT NULL,
	"type"	ENUM		NOT NULL,
	"status"	ENUM		NOT NULL,
	"message"	VARCHAR		NULL,
	"startedAt"	TIMESTAMP		NULL,
	"expiredAt"	TIMESTAMP		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_REQUESTS"."id" IS '요청 ID';

COMMENT ON COLUMN "TB_REQUESTS"."creatorId" IS '요청자 프로필 ID';

COMMENT ON COLUMN "TB_REQUESTS"."type" IS '요청 유형';

COMMENT ON COLUMN "TB_REQUESTS"."status" IS '요청 상태';

COMMENT ON COLUMN "TB_REQUESTS"."message" IS '요청자의 메세지';

COMMENT ON COLUMN "TB_REQUESTS"."startedAt" IS '요청 유효시작시간';

COMMENT ON COLUMN "TB_REQUESTS"."expiredAt" IS '요청 유효마감시간';

COMMENT ON COLUMN "TB_REQUESTS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_REQUESTS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_BEACON_RECORDS" (
	"id"	UUID		NOT NULL,
	"beaconId"	UUID		NOT NULL,
	"workRecordId"	UUID		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_BEACON_RECORDS"."id" IS '비콘기록 ID';

COMMENT ON COLUMN "TB_BEACON_RECORDS"."beaconId" IS '비콘 ID';

COMMENT ON COLUMN "TB_BEACON_RECORDS"."workRecordId" IS '근무기록 ID';

COMMENT ON COLUMN "TB_BEACON_RECORDS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_BEACON_RECORDS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_WORK_RECORDS" (
	"id"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL,
	"startAt"	TIMESTAMP		NOT NULL,
	"endAt"	TIMESTAMP		NOT NULL,
	"totalSecond"	INT		NOT NULL,
	"isOvertime"	BOOLEAN		NOT NULL,
	"workType"	ENUM		NOT NULL,
	"status"	ENUM	DEFAULT approved	NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL,
	"checkInMethod"	ENUM		NOT NULL,
	"checkOutMethod"	ENUM		NOT NULL
);

COMMENT ON COLUMN "TB_WORK_RECORDS"."id" IS '근무기록 ID';

COMMENT ON COLUMN "TB_WORK_RECORDS"."profileId" IS '프로필 ID';

COMMENT ON COLUMN "TB_WORK_RECORDS"."startAt" IS '근무 시작 시간';

COMMENT ON COLUMN "TB_WORK_RECORDS"."endAt" IS '근무 종료 시간';

COMMENT ON COLUMN "TB_WORK_RECORDS"."totalSecond" IS '전체 근무 시간 (초)';

COMMENT ON COLUMN "TB_WORK_RECORDS"."isOvertime" IS '초과 근무 여부';

COMMENT ON COLUMN "TB_WORK_RECORDS"."workType" IS '근무 유형 (재택...)';

COMMENT ON COLUMN "TB_WORK_RECORDS"."status" IS '근무 기록 승인 상태';

COMMENT ON COLUMN "TB_WORK_RECORDS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_WORK_RECORDS"."updatedAt" IS '수정일자';

COMMENT ON COLUMN "TB_WORK_RECORDS"."checkInMethod" IS '출근시 사용한 기록 방법';

COMMENT ON COLUMN "TB_WORK_RECORDS"."checkOutMethod" IS '퇴근시 사용한 기록 방법';

CREATE TABLE "TB_WORK_POLICIES" (
	"id"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"description"	TEXT		NULL,
	"workStartTime"	TIME		NULL,
	"workEndTime"	TIME		NULL,
	"breakStartTime"	TIME		NULL,
	"breakEndTime"	TIME		NULL,
	"dailyWorkHour"	INT		NULL,
	"weeklyWorkHour"	INT		NULL,
	"monthlyWorkHour"	INT		NULL,
	"isFlexible"	BOOLEAN		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_WORK_POLICIES"."id" IS '근로정책 ID';

COMMENT ON COLUMN "TB_WORK_POLICIES"."name" IS '근로정책명';

COMMENT ON COLUMN "TB_WORK_POLICIES"."description" IS '근로 정책 설명';

COMMENT ON COLUMN "TB_WORK_POLICIES"."workStartTime" IS '기본 근무 시작시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."workEndTime" IS '기본 근무 종료시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."breakStartTime" IS '기본 휴게 시작시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."breakEndTime" IS '기본 휴게 종료시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."dailyWorkHour" IS '일별 최소 근로 시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."weeklyWorkHour" IS '주별 최소 근로 시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."monthlyWorkHour" IS '월별 최소 근로 시간';

COMMENT ON COLUMN "TB_WORK_POLICIES"."isFlexible" IS '유연근무제 여부';

COMMENT ON COLUMN "TB_WORK_POLICIES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_WORK_POLICIES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_SALARY_RECEIPTS" (
	"id"	UUID		NOT NULL,
	"salaryId"	UUID		NOT NULL,
	"title"	FLOAT		NOT NULL,
	"payment"	FLOAT		NOT NULL,
	"paidAt"	TIMESTAMP		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."id" IS '급여 영수증 ID';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."salaryId" IS '연봉 ID';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."title" IS '지급 항목명';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."payment" IS '지급 금액';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."paidAt" IS '지급일자';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_SALARY_RECEIPTS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_FILES" (
	"id"	UUID		NOT NULL,
	"uploaderId"	UUID		NULL,
	"uploadType"	ENUM		NOT NULL,
	"originalName"	VARCHAR		NOT NULL,
	"ext"	VARCHAR		NULL,
	"path"	VARCHAR		NOT NULL,
	"size"	INT		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"deletedAt"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "TB_FILES"."id" IS '파일 ID';

COMMENT ON COLUMN "TB_FILES"."uploaderId" IS '업로더 프로필 ID';

COMMENT ON COLUMN "TB_FILES"."uploadType" IS '파일 업로드 유형';

COMMENT ON COLUMN "TB_FILES"."originalName" IS '원본 파일명';

COMMENT ON COLUMN "TB_FILES"."ext" IS '파일 확장자명';

COMMENT ON COLUMN "TB_FILES"."path" IS '파일 절대 경로';

COMMENT ON COLUMN "TB_FILES"."size" IS '파일 데이터 크기(BYTE)';

COMMENT ON COLUMN "TB_FILES"."createdAt" IS '파일이 업로드된 일자';

COMMENT ON COLUMN "TB_FILES"."deletedAt" IS '파일이 삭제된 일자';

CREATE TABLE "TB_SALARIES" (
	"id"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL,
	"isCurrent"	BOOLEAN		NOT NULL,
	"payment"	FLOAT		NOT NULL,
	"currencyCode"	VARCHAR		NOT NULL,
	"currencyDigits"	INT		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_SALARIES"."id" IS '연봉 ID';

COMMENT ON COLUMN "TB_SALARIES"."profileId" IS '프로필 ID';

COMMENT ON COLUMN "TB_SALARIES"."isCurrent" IS '연봉 적용 여부';

COMMENT ON COLUMN "TB_SALARIES"."payment" IS '총 연봉 금액';

COMMENT ON COLUMN "TB_SALARIES"."currencyCode" IS 'ISO4217 통화 코드';

COMMENT ON COLUMN "TB_SALARIES"."currencyDigits" IS 'ISO4217 통화 번호';

COMMENT ON COLUMN "TB_SALARIES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_SALARIES"."updatedAt" IS '수정일자';

CREATE TABLE "TB_APPROVALS" (
	"id"	UUID		NOT NULL,
	"requestId"	UUID		NOT NULL,
	"approverId"	UUID		NULL,
	"seq"	INT		NOT NULL,
	"status"	ENUM		NOT NULL,
	"message"	VARCHAR		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_APPROVALS"."id" IS '결재 순서 ID';

COMMENT ON COLUMN "TB_APPROVALS"."requestId" IS '요청 ID';

COMMENT ON COLUMN "TB_APPROVALS"."approverId" IS '결재자 프로필 ID';

COMMENT ON COLUMN "TB_APPROVALS"."seq" IS '결재 순서';

COMMENT ON COLUMN "TB_APPROVALS"."status" IS '결재 상태';

COMMENT ON COLUMN "TB_APPROVALS"."message" IS '결재자의 메세지';

COMMENT ON COLUMN "TB_APPROVALS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_APPROVALS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_PROFILE_AUDIT_LOGS" (
	"id"	UUID		NOT NULL,
	"type"	ENUM		NOT NULL,
	"target"	ENUM		NOT NULL,
	"beforeValue"	VARCHAR		NOT NULL,
	"afterValue"	VARCHAR		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."id" IS '프로필로그 ID';

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."type" IS '로그 유형';

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."target" IS '프로필의 키값';

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."beforeValue" IS '변경 전의 값';

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."afterValue" IS '변경 후의 값';

COMMENT ON COLUMN "TB_PROFILE_AUDIT_LOGS"."createdAt" IS '로그 생성일자';

CREATE TABLE "TB_BREAK_RECORDS" (
	"id"	UUID		NOT NULL,
	"workRecordId"	UUID		NOT NULL,
	"startAt"	TIMESTAMP		NOT NULL,
	"endAt"	TIMESTAMP		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_BREAK_RECORDS"."id" IS '휴게기록 ID';

COMMENT ON COLUMN "TB_BREAK_RECORDS"."workRecordId" IS '근무기록 ID';

COMMENT ON COLUMN "TB_BREAK_RECORDS"."startAt" IS '휴게 시작 시간';

COMMENT ON COLUMN "TB_BREAK_RECORDS"."endAt" IS '휴게 종료 시간';

COMMENT ON COLUMN "TB_BREAK_RECORDS"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_BREAK_RECORDS"."updatedAt" IS '수정일자';

CREATE TABLE "TB_LEAVE_BALANCES" (
	"id"	UUID		NOT NULL,
	"profileId"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"type"	ENUM		NOT NULL,
	"isPaid"	BOOLEAN		NOT NULL,
	"totalMinutes"	INT		NOT NULL,
	"totalLeft"	INT		NOT NULL,
	"startAt"	TIMESTAMP		NOT NULL,
	"expireAt"	TIMESTAMP		NOT NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL,
	"isAvailable"	BOOLEAN		NOT NULL
);

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."id" IS '보유 휴가 ID';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."profileId" IS '프로필 ID';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."name" IS '휴가 이름';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."type" IS '휴가 유형';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."isPaid" IS '유급 휴가 여부';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."totalMinutes" IS '지급된 총 휴가 시간';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."totalLeft" IS '보유한 총 휴가 시간';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."startAt" IS '휴가 유효일자 시작시간';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."expireAt" IS '휴가 유효일자 마감시간';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."updatedAt" IS '수정일자';

COMMENT ON COLUMN "TB_LEAVE_BALANCES"."isAvailable" IS '사용가능여부';

CREATE TABLE "TB_LEAVE_POLICIES" (
	"id"	UUID		NOT NULL,
	"name"	VARCHAR		NOT NULL,
	"description"	TEXT		NULL,
	"createdAt"	TIMESTAMP		NOT NULL,
	"updatedAt"	TIMESTAMP		NOT NULL
);

COMMENT ON COLUMN "TB_LEAVE_POLICIES"."id" IS '휴가정책 ID';

COMMENT ON COLUMN "TB_LEAVE_POLICIES"."name" IS '휴가정책명';

COMMENT ON COLUMN "TB_LEAVE_POLICIES"."description" IS '휴가 정책 설명';

COMMENT ON COLUMN "TB_LEAVE_POLICIES"."createdAt" IS '생성일자';

COMMENT ON COLUMN "TB_LEAVE_POLICIES"."updatedAt" IS '수정일자';

ALTER TABLE "TB_COMPANIES" ADD CONSTRAINT "PK_TB_COMPANIES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_PROFILE_POSITIONS" ADD CONSTRAINT "PK_TB_PROFILE_POSITIONS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_POSITIONS" ADD CONSTRAINT "PK_TB_POSITIONS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_LEAVES" ADD CONSTRAINT "PK_TB_LEAVES" PRIMARY KEY (
	"id",
	"leaveBalanceId",
	"profileId"
);

ALTER TABLE "TB_DOCUMENT_FILES" ADD CONSTRAINT "PK_TB_DOCUMENT_FILES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_COMPANY_POLICIES" ADD CONSTRAINT "PK_TB_COMPANY_POLICIES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_DOCUMENTS" ADD CONSTRAINT "PK_TB_DOCUMENTS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_BANKS" ADD CONSTRAINT "PK_TB_BANKS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_PROFILES" ADD CONSTRAINT "PK_TB_PROFILES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_TEAM_PROFILES" ADD CONSTRAINT "PK_TB_TEAM_PROFILES" PRIMARY KEY (
	"id"
);

ALTER TABLE "REDIS:BREAK_SESSIONS" ADD CONSTRAINT "PK_REDIS:BREAK_SESSIONS" PRIMARY KEY (
	"{profileId}_break"
);

ALTER TABLE "REDIS:WORK_SESSIONS" ADD CONSTRAINT "PK_REDIS:WORK_SESSIONS" PRIMARY KEY (
	"{profileId}_work"
);

ALTER TABLE "TB_USERS" ADD CONSTRAINT "PK_TB_USERS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_BEACONS" ADD CONSTRAINT "PK_TB_BEACONS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_ACCOUNT_LOGS" ADD CONSTRAINT "PK_TB_ACCOUNT_LOGS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_TEAMS" ADD CONSTRAINT "PK_TB_TEAMS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_BANK_ACCOUNTS" ADD CONSTRAINT "PK_TB_BANK_ACCOUNTS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_REQUESTS" ADD CONSTRAINT "PK_TB_REQUESTS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_BEACON_RECORDS" ADD CONSTRAINT "PK_TB_BEACON_RECORDS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_WORK_RECORDS" ADD CONSTRAINT "PK_TB_WORK_RECORDS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_WORK_POLICIES" ADD CONSTRAINT "PK_TB_WORK_POLICIES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_SALARY_RECEIPTS" ADD CONSTRAINT "PK_TB_SALARY_RECEIPTS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_FILES" ADD CONSTRAINT "PK_TB_FILES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_SALARIES" ADD CONSTRAINT "PK_TB_SALARIES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_APPROVALS" ADD CONSTRAINT "PK_TB_APPROVALS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_PROFILE_AUDIT_LOGS" ADD CONSTRAINT "PK_TB_PROFILE_AUDIT_LOGS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_BREAK_RECORDS" ADD CONSTRAINT "PK_TB_BREAK_RECORDS" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_LEAVE_BALANCES" ADD CONSTRAINT "PK_TB_LEAVE_BALANCES" PRIMARY KEY (
	"id",
	"profileId"
);

ALTER TABLE "TB_LEAVE_POLICIES" ADD CONSTRAINT "PK_TB_LEAVE_POLICIES" PRIMARY KEY (
	"id"
);

ALTER TABLE "TB_LEAVES" ADD CONSTRAINT "FK_TB_LEAVE_BALANCES_TO_TB_LEAVES_1" FOREIGN KEY (
	"leaveBalanceId"
)
REFERENCES "TB_LEAVE_BALANCES" (
	"id"
);

ALTER TABLE "TB_LEAVES" ADD CONSTRAINT "FK_TB_LEAVE_BALANCES_TO_TB_LEAVES_2" FOREIGN KEY (
	"profileId"
)
REFERENCES "TB_LEAVE_BALANCES" (
	"profileId"
);

ALTER TABLE "TB_LEAVE_BALANCES" ADD CONSTRAINT "FK_TB_PROFILES_TO_TB_LEAVE_BALANCES_1" FOREIGN KEY (
	"profileId"
)
REFERENCES "TB_PROFILES" (
	"id"
);

